// eslint-disable-next-line import/prefer-default-export
export const SET_ADMIN_PRODUCT_LIST = 'SET_ADMIN_PRODUCT_LIST';
export const SET_ADMIN_PRODUCT_SOLD = 'SET_ADMIN_PRODUCT_SOLD';
export const SET_ADMIN_PRODUCT_TAGS = 'SET_ADMIN_PRODUCT_TAGS';
export const SET_ADMIN_PRODUCT_DETAIL = 'SET_ADMIN_PRODUCT_DETAIL';
export const REMOVE_NEW_PRODUCT_ITEM = 'REMOVE_NEW_PRODUCT_ITEM';
export const CLEAR_ALL_ADMIN_PRODUCT = 'CLEAR_ALL_ADMIN_PRODUCT';
export const ONCHANGE_ADMIN_PRODUCT = 'ONCHANGE_ADMIN_PRODUCT';
export const SET_NEW_ADMIN_PRODUCT = 'SET_NEW_ADMIN_PRODUCT';
export const UPDATE_ADMIN_PRODUCT = 'UPDATE_ADMIN_PRODUCT';
export const SET_PRODUCT_STATUS = 'SET_PRODUCT_STATUS';
export const SET_ADMIN_PRODUCT_COMMENT = 'SET_ADMIN_PRODUCT_COMMENT';
export const REMOVE_ADMIN_PRODUCT_COMMENT = 'REMOVE_ADMIN_PRODUCT_COMMENT';
export const SET_ADMIN_PRODUCT_ASSET = 'SET_ADMIN_PRODUCT_ASSET';
export const REMOVE_ADMIN_PRODUCT_ASSET = 'REMOVE_ADMIN_PRODUCT_ASSET';
export const REMOVE_ADMIN_PRODUCT_TAG = 'REMOVE_ADMIN_PRODUCT_TAG';
export const SET_COVER_PHOTO_ORDER = 'SET_COVER_PHOTO_ORDER';
export const SET_PRODUCT_COMMENT_LIST = 'SET_PRODUCT_COMMENT_LIST';
