export const GETTING_CLIENT_DETAILS = 'GETTING_CLIENT_DETAILS';
export const GET_CLIENT_DETAILS_FAILURE = 'GET_CLIENT_DETAILS_FAILURE';
export const GET_CLIENT_DETAILS_SUCCESS = 'GET_CLIENT_DETAILS_SUCCESS';
export const UPDATE_CLIENT_DETAIL_SUCCESS = 'UPDATE_CLIENT_DETAIL_SUCCESS';
export const UPDATE_CLIENT_DETAILS_FROM_FORM = 'UPDATE_CLIENT_DETAILS_FROM_FORM';
