export const FETCH_ALL_NOTIFICATIONS = 'FETCH_ALL_ NOTIFICATIONS';
export const START_FETCH_ALL_NOTIFICATIONS = 'START_FETCH_ALL_NOTIFICATIONS';
export const FETCH_ONE_NOTIFICATION = 'FETCH_ONE-NOTIFICATION';
export const START_FETCH_ONE_NOTIFICATION = 'START_FETCH_ONE_NOTIFICATION';
export const GETTING_UNREAD_NOTIFICATION_COUNT = 'GETTING_UNREAD_NOTIFICATION_COUNT';
export const GET_UNREAD_NOTIFICATION_COUNT_SUCCESS = 'GET_UNREAD_NOTIFICATION_COUNT_SUCCESS';
export const GET_UNREAD_NOTIFICATION_COUNT_FAILURE = 'GET_UNREAD_NOTIFICATION_COUNT_FAILURE';
export const MARK_ALL_NOTIFICATION_AS_READ_SUCCESS = 'MARK_ALL_NOTIFICATION_AS_READ_SUCCESS';
